--- zita-alsa-pcmi-0.3.2/apps/Makefile.orig	2021-09-26 20:12:49.143936028 +0200
+++ zita-alsa-pcmi-0.3.2/apps/Makefile	2021-09-26 20:18:13.738844213 +0200
@@ -25,7 +25,7 @@ BINDIR ?= $(PREFIX)/bin
 
 VERSION = "0.3.2"
 CPPFLAGS +=  -MMD -MP -DVERSION=\"$(VERSION)\"
-CXXFLAGS += -O2 -Wall
+CXXFLAGS += -Wall
 
 
 all:	alsa_loopback alsa_delay
@@ -48,7 +48,7 @@ $(ALSA_DELAY_O):
 
 
 install:	all
-	install -d $(BINDIR)
+	install -d $(DESTDIR)$(BINDIR)
 	install -m 755 alsa_loopback  $(DESTDIR)$(BINDIR)
 	install -m 755 alsa_delay     $(DESTDIR)$(BINDIR)
 
--- zita-alsa-pcmi-0.3.2/source/Makefile.orig	2018-08-24 20:41:30.000000000 +0200
+++ zita-alsa-pcmi-0.3.2/source/Makefile	2021-09-26 20:19:30.798426745 +0200
@@ -30,8 +30,7 @@ MINVERS = 3.2
 VERSION = $(MAJVERS).$(MINVERS)
 
 CPPFLAGS += -DVERSION=\"$(VERSION)\" -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS
-CXXFLAGS += -O2 -Wall -fPIC
-CXXFLAGS += -march=native
+CXXFLAGS += -Wall -fPIC
 LDLFAGS +=
 LDLIBS +=
 
@@ -53,7 +52,7 @@ install:	$(ZITA-ALSA-PCMI_MIN)
 	install -d $(DESTDIR)$(LIBDIR)
 	install -m 644 $(ZITA-ALSA-PCMI_H) $(DESTDIR)$(INCDIR)
 	install -m 755 $(ZITA-ALSA-PCMI_MIN) $(DESTDIR)$(LIBDIR)
-	ldconfig
+	-/sbin/ldconfig -n -N $(DESTDIR)$(LIBDIR)
 	ln -sf $(ZITA-ALSA-PCMI_MIN) $(DESTDIR)$(LIBDIR)/$(ZITA-ALSA-PCMI_SO)
 
 uninstall:
